/**
 * Production-readiness report.
 *
 * The release rehearsal (`scripts/production-readiness.ts`) runs a set of
 * checks and hands their results here to be summarized and rendered as a
 * committed Markdown report. The report records pass/fail evidence and the
 * remaining human launch dependencies, and it never silently relaxes a check:
 * a `manual` item stays a tracked human dependency (it can never be
 * auto-passed), and any `fail` blocks the launch outright.
 */

export type ReadinessStatus = "pass" | "fail" | "manual";

export interface ReadinessCheck {
  /** Short name of what was checked. */
  name: string;
  status: ReadinessStatus;
  /** Human-readable evidence — the observed proof, never a secret value. */
  evidence: string;
}

export type OverallStatus = "ready" | "pending" | "blocked";

export interface ReadinessSummary {
  overallStatus: OverallStatus;
  hasFailures: boolean;
  hasManual: boolean;
  counts: Record<ReadinessStatus, number>;
}

const STATUS_LABEL: Record<ReadinessStatus, string> = {
  pass: "✅ pass",
  fail: "❌ fail",
  manual: "🔶 manual",
};

const OVERALL_LABEL: Record<OverallStatus, string> = {
  ready: "READY FOR PRODUCTION",
  pending: "PENDING HUMAN LAUNCH DEPENDENCIES",
  blocked: "BLOCKED",
};

/**
 * Reduces the checks to an overall verdict. Ready requires that every check
 * passed and at least one check ran; outstanding `manual` items keep the verdict
 * `pending`; any `fail` makes it `blocked`.
 */
export function summarizeReadiness(
  checks: readonly ReadinessCheck[],
): ReadinessSummary {
  const counts: Record<ReadinessStatus, number> = {
    pass: 0,
    fail: 0,
    manual: 0,
  };
  for (const check of checks) {
    counts[check.status] += 1;
  }

  const hasFailures = counts.fail > 0;
  const hasManual = counts.manual > 0;

  let overallStatus: OverallStatus;
  if (hasFailures || checks.length === 0) {
    overallStatus = "blocked";
  } else if (hasManual) {
    overallStatus = "pending";
  } else {
    overallStatus = "ready";
  }

  return { overallStatus, hasFailures, hasManual, counts };
}

interface RenderReportOptions {
  checks: readonly ReadinessCheck[];
  /** ISO-8601 timestamp for when the rehearsal ran. */
  generatedAt: string;
}

function escapePipes(value: string): string {
  return value.replace(/\|/g, "\\|");
}

/**
 * Renders the readiness report as Markdown, suitable to commit at
 * `docs/production-readiness.md`.
 */
export function renderProductionReadinessReport({
  checks,
  generatedAt,
}: RenderReportOptions): string {
  const summary = summarizeReadiness(checks);
  const manualChecks = checks.filter((check) => check.status === "manual");

  const rows = checks
    .map(
      (check) =>
        `| ${escapePipes(check.name)} | ${STATUS_LABEL[check.status]} | ${escapePipes(check.evidence)} |`,
    )
    .join("\n");

  const dependencies =
    manualChecks.length === 0
      ? "None. Every check is automated and passing."
      : manualChecks
          .map((check) => `- **${check.name}** — ${check.evidence}`)
          .join("\n");

  return `# Production Readiness Report

> Generated by \`pnpm release:rehearsal\` (\`scripts/production-readiness.ts\`).
> Do not edit by hand — rerun the rehearsal to refresh it.

- **Generated:** ${generatedAt}
- **Overall status:** ${OVERALL_LABEL[summary.overallStatus]}
- **Checks:** ${summary.counts.pass} passed · ${summary.counts.fail} failed · ${summary.counts.manual} manual

## Checks

| Check | Status | Evidence |
| ----- | ------ | -------- |
${rows}

## Remaining human launch dependencies

${dependencies}
`;
}
